### ISSUE TITLE
🛑 Broken Site (Negative Control) is down

### ISSUE THREAD

**Issue by ttsukagoshi** [ttsukagoshi/website-status-by-Upptime#3]
In [`b09a26c`](https://github.com/ttsukagoshi/website-status-by-Upptime/commit/b09a26c181584601d664e1d5aff5abcee5170b0d
), Broken Site (Negative Control) (https://thissitedoesnotexist.com) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by ippr** [comment]
Negative control test complete
